### ISSUE TITLE
推主id是什么啊

### ISSUE THREAD

**Issue by PackageInstaller** [nek0us/nonebot-plugin-twitter#1]
![image](https://github.com/nek0us/nonebot-plugin-twitter/assets/80018096/16beb36b-2f50-4a30-85b0-60535895043c)
如图，怎么设置都不对

**Comment by nek0us** [comment]
Bearer Token 正确配置了吗

**Comment by PackageInstaller** [comment]
> Bearer Token 正确配置了吗

bearer_token = "xxxxx"这样吗，配置好了

**Comment by nek0us** [comment]
是的  xxx有替换成正确的 Bearer Token 值吗？
然后 配置文件里还有其他 同名bearer_token变量吗？

**Comment by PackageInstaller** [comment]
> 是的  xxx有替换成正确的 Bearer Token 值吗？
> 然后 配置文件里还有其他 同名bearer_token变量吗？

有
没有

**Comment by nek0us** [comment]
是通过配置proxy 代理的方式使用插件吗

**Comment by nek0us** [comment]
试试配置一下 twitter_proxy 变量，值为 ip:clash端口 呢

**Comment by smaxad47** [comment]
一样的问题，bearer_token 配置好了，服务器在国外不需要代理可以访问推

**Comment by Nenot233** [comment]
一样的问题，bearer_token 配置好了,也代理了也是报未找到

**Comment by nek0us** [comment]
更一下0.0.7版本，配置文件里添加 twitter_debug=True
然后截一下启动时输出的日志，也可以先减少加载的插件以便于日志获取
![VL}TK6W$ELJR% SO}M2SIUJ](https://github.com/nek0us/nonebot-plugin-twitter/assets/57703506/d0695a4f-fcd5-42a1-bd41-a4769cf113a6)

**Comment by nek0us** [comment]
> 一样的问题，bearer_token 配置好了，服务器在国外不需要代理可以访问推 "When authenticating requests to the Twitter API v2 endpoints, you must use keys and tokens from a Twitter developer App that is attached to a Project. You can create a project via the developer portal." 错误是这个 不能用bearer_token吗

也许需要先创建一个project app

**Comment by Nenot233** [comment]
![image](https://github.com/nek0us/nonebot-plugin-twitter/assets/108965579/f887f8ec-4376-4606-afd8-627dc99c1bc2)

**Comment by nek0us** [comment]
> ![image](https://user-images.githubusercontent.com/108965579/243565092-f887f8ec-4376-4606-afd8-627dc99c1bc2.png)

配置文件里的代理是不带 http:// 的，可以看一下新更新的readme里的示例图

**Comment by smaxad47** [comment]
> 

创建好了 生成token的APP也是在project里的

**Comment by nek0us** [comment]
> > 
> 
> 创建好了 生成token的APP也是在project里的

然后可以了吗

**Comment by Nenot233** [comment]
> > ![image](https://user-images.githubusercontent.com/108965579/243565092-f887f8ec-4376-4606-afd8-627dc99c1bc2.png)
> 
> 配置文件里的代理是不带 http:// 的，可以看一下新更新的readme里的示例图

06-06 14:24:10 [INFO] nonebot_plugin_twitter | bearer_token 读取成功
06-06 14:24:10 [INFO] nonebot_plugin_twitter | twitter_proxy 读取成功
06-06 14:24:10 [INFO] nonebot_plugin_twitter | twitter_debug 开启成功
06-06 14:24:10 [INFO] nonebot_plugin_twitter | 已读取 twitter proxy {'http': '127.0.0.1:7890', 'https': '127.0.0.1:7890'}
06-06 14:24:11 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_twitter"

**Comment by smaxad47** [comment]
> > > 
> > 
> > 
> > 创建好了 生成token的APP也是在project里的
> 
> 然后可以了吗

不行，我看了下Twitter API v2里免费版的权限，对照了一下tweepy，感觉免费版的不能查询其他用户，使用get_me()到是可以获取到自己账号的资料，但用的不是Bearer Token了

**Comment by Nenot233** [comment]
> > > > 
> > > 
> > > 
> > > 创建好了 生成token的APP也是在project里的
> > 
> > 
> > 然后可以了吗
> 
> 不行，我看了下Twitter API v2里免费版的权限，对照了一下tweepy，感觉免费版的不能查询其他用户，使用get_me()到是可以获取到自己账号的资料，但用的不是Bearer Token了

![image](https://github.com/nek0us/nonebot-plugin-twitter/assets/108965579/4aed5949-ab54-4804-a111-3f1209f29cc2)
![image](https://github.com/nek0us/nonebot-plugin-twitter/assets/108965579/b8aec933-3d4c-4d0b-b968-ef57b725c2b2)
免费版好像能查，但是对次数有限制

**Comment by smaxad47** [comment]
User lookup下 只有GET /2/users/me 这个Endpoint可以访问 其他都不行，会提示Unauthorized。

**Comment by nek0us** [comment]
> User lookup下 只有GET /2/users/me 这个Endpoint可以访问 其他都不行，会提示Unauthorized。 切换到Basic版本，User lookup下的Endpoint就有GET /2/users/:id可以访问了 应该是免费版的问题 楼上其他人应该都是同样的问题

我也未曾给api付费，查看文档，免费版也有访问权限 
[1](https://developer.twitter.com/en/docs/twitter-api/tweet-caps) 
[2](https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#item0) 
[3](https://developer.twitter.com/en/docs/authentication/guides/v2-authentication-mapping)
这个插件的作用只有根据用户名查询主键id、查询用户推文和根据推文id查询内容的功能。
也许是api申请的问题，我的账号申请较久，我尝试回忆一下是否漏掉了什么步骤。

**Comment by Nenot233** [comment]
> > > > ![image](https://user-images.githubusercontent.com/108965579/243565092-f887f8ec-4376-4606-afd8-627dc99c1bc2.png)
> > > 
> > > 
> > > 配置文件里的代理是不带 http:// 的，可以看一下新更新的readme里的示例图
> > 
> > 
> > 06-06 14:24:10 [INFO] nonebot_plugin_twitter | bearer_token 读取成功 06-06 14:24:10 [INFO] nonebot_plugin_twitter | twitter_proxy 读取成功 06-06 14:24:10 [INFO] nonebot_plugin_twitter | twitter_debug 开启成功 06-06 14:24:10 [INFO] nonebot_plugin_twitter | 已读取 twitter proxy {'http': '127.0.0.1:7890', 'https': '127.0.0.1:7890'} 06-06 14:24:11 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_twitter"
> 
> 对，就是这样，不过你这个没有在配置文件里添加 twitter_debug=True 所以日志不全，但你可以先测试一下能不能正常使用

![image](https://github.com/nek0us/nonebot-plugin-twitter/assets/108965579/147141ed-223a-4861-923b-42492f69aa28)

**Comment by Nenot233** [comment]
![image](https://github.com/nek0us/nonebot-plugin-twitter/assets/108965579/9071775a-613a-499c-8116-17f77410526a)
![image](https://github.com/nek0us/nonebot-plugin-twitter/assets/108965579/01f99cd9-0bcf-43e8-862c-a1787484ef64)
注释掉这几行会影响插件吗？

**Comment by nek0us** [comment]
> 

不会，这是适配nb2.0.0的元数据，是为了规范的。rc版本可以删掉 __plugin_meta__ 变量，不影响运行。

**Comment by Nenot233** [comment]
> > 
> 
> 不会，这是适配nb2.0.0的元数据，是为了规范的。rc版本可以删掉 **plugin_meta** 变量，不影响运行。

目前nonebot2版本是RC4这个有影响吗？

**Comment by nek0us** [comment]
> > > 
> > 
> > 
> > 不会，这是适配nb2.0.0的元数据，是为了规范的。rc版本可以删掉 **plugin_meta** 变量，不影响运行。
> 
> 目前nonebot2版本是RC4这个有影响吗？

plugin_meta可以删掉，没影响。插件功能上用rc4没区别。

**Comment by Nenot233** [comment]
> > User lookup下 只有GET /2/users/me 这个Endpoint可以访问 其他都不行，会提示Unauthorized。 切换到Basic版本，User lookup下的Endpoint就有GET /2/users/:id可以访问了 应该是免费版的问题 楼上其他人应该都是同样的问题
> 
> 我也未曾给api付费，查看文档，免费版也有访问权限 [1](https://developer.twitter.com/en/docs/twitter-api/tweet-caps) [2](https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#item0) [3](https://developer.twitter.com/en/docs/authentication/guides/v2-authentication-mapping) 这个插件的作用只有根据用户名查询主键id、查询用户推文和根据推文id查询内容的功能。 也许是api申请的问题，我的账号申请较久，我尝试回忆一下是否漏掉了什么步骤。

![image](https://github.com/nek0us/nonebot-plugin-twitter/assets/108965579/e6324e0f-e6a1-43bb-8d2a-9e7e1a59d08a)
怎么感觉是因为API注册时间不同开放的东西不同

**Comment by zhulinyv** [comment]
同样的问题, mark 一下

**Comment by nek0us** [comment]
重写了插件，现在不需要token了。
本次为破坏性更新，配置文件格式有更改，详见readme。
原有的关注列表也需重新关注。

**Comment by nek0us** [comment]
> > 重写了插件，现在不需要token了。 本次为破坏性更新，配置文件格式有更改，详见readme。 原有的关注列表也需重新关注。
> 
> 06-11 13:16:14 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_twitter) failed. Traceback (most recent call last): File "", line 17, in File "C:\gambot.venv\lib\site-packages\nonebot__init__.py", line 309, in run get_driver().run(*args, **kwargs) File "C:\gambot.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run uvicorn.run( File "C:\gambot.venv\lib\site-packages\uvicorn\main.py", line 578, in run server.run() File "C:\gambot.venv\lib\site-packages\uvicorn\server.py", line 61, in run return asyncio.run(self.serve(sockets=sockets)) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 634, in run_unti l_complete self.run_forever() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_f orever super().run_forever() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 601, in run_fore ver self._run_once() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1905, in _run_on ce handle._run() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run self._context.run(self._callback, *self._args) File "C:\gambot.venv\lib\site-packages\nonebot\message.py", line 467, in check_and_run_matcher await _run_matcher(
> 
> > File "C:\gambot.venv\lib\site-packages\nonebot\message.py", line 419, in _run_matcher
> > await matcher.run(bot, event, state, stack, dependency_cache)
> > File "C:\gambot.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
> > await self.simple_run(bot, event, state, stack, dependency_cache)
> > File "C:\gambot.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
> > await handler(
> > File "C:\gambot.venv\lib\site-packages\nonebot\dependencies__init__.py", line 108, in **call**
> > return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> > File "C:\gambot.venv\lib\site-packages\nonebot_plugin_twitter__init__.py", line 196, in save_handle
> > user_info = await get_user_info(data[0])
> > File "C:\gambot.venv\lib\site-packages\nonebot_plugin_twitter\api.py", line 22, in get_user_info
> > soup = BeautifulSoup(res.text,"lxml")
> > File "C:\gambot.venv\lib\site-packages\bs4__init__.py", line 250, in **init**
> > raise FeatureNotFound(
> > bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser
> > library?
> 
> 这是什么错误?

是我忘了更新依赖包，一会试一下0.1.1版本

**Comment by PackageInstaller** [comment]
应该是没问题了。我这边能关注了

**Comment by PackageInstaller** [comment]
> > 应该是没问题了。我这边能关注了
> 
> 你说得对 但是依赖只能手动下载

啥依赖

**Comment by nek0us** [comment]
> > 啥依赖
> 
> 你说应该没问题的时候 我pip -U了几次还是不行 然后我就乱翻 发现没有lxml手动安装上就好了

0.1.1版本已经添加了 lxml 的依赖包，如果还会出现问题的话下个版本我就全改成python内置库吧，这是个小问题

**Comment by PackageInstaller** [comment]
> > 啥依赖
> 
> 你说应该没问题的时候 我pip -U了几次还是不行 然后我就乱翻 发现没有lxml手动安装上就好了

我用的是真寻，他自己带这个依赖

**Comment by nek0us** [comment]
> > 啥依赖
> 
> 你说应该没问题的时候 我pip -U了几次还是不行 然后我就乱翻 发现没有lxml手动安装上就好了

看了下pypi，我傻了，是我更新后忘了推送了。不好意思

**Comment by nek0us** [comment]
> > 看了下pypi，我傻了，是我更新后忘了推送了。不好意思
> 
> 我就说怎么还是1.0🥺

已更新

**Comment by nek0us** [comment]
修了一些小bug，建议更一下最新版

**Comment by PackageInstaller** [comment]
那我close咯
