### ISSUE TITLE
自己搭建nitter读取失败

### ISSUE THREAD

**Issue by PackageInstaller** [nek0us/nonebot-plugin-twitter#12]
按照github上说明自建了一个
![image](https://github.com/nek0us/nonebot-plugin-twitter/assets/80018096/1978548e-bf89-4187-b83f-9ead430f896a)
![image](https://github.com/nek0us/nonebot-plugin-twitter/assets/80018096/d9e457e7-5c07-4c7f-916b-5593fedd95a2)

读取失败
![image](https://github.com/nek0us/nonebot-plugin-twitter/assets/80018096/d43f7338-0cca-4f85-b3da-669f02b893bc)

是我哪里设置错了吗，这玩意根本找不到教程啊

**Comment by nek0us** [comment]
我也不清楚，或许这个issue该提到nitter那。不过自从改名X之后，nitter也不稳定了，还不知道它们有没有找到修复方法。更新日志里的那个url是可以用的，虽然有些延迟。

**Comment by PackageInstaller** [comment]
只能先问候马斯克了（
