### ISSUE TITLE
这是什么报错（?）

### ISSUE THREAD

**Issue by Nenot233** [nek0us/nonebot-plugin-twitter#18]
01-02 13:05:01 [WARNING] nonebot_plugin_twitter | 通过 user_name EGOIST_myEgo 获取时间线失败：403 �� M�z}u���t��      "��=E �HqAqj&���ʑ�QXJ�J�e��M<E�p4�p@��jޢ���
Lw~X��3��j���oq����y���9�S����t�O3��}||�"�Ni�Ա ����)��a����]�l�e.r�\��;n ���a���/��V��"U�!N�x��k�����?��dJ����?��)����F
x}�m�����_��S$��d4/��$�Qޤ@��i��&�3�|2�E��a�x��~s�T�i^=�]<�۶���4����f�����l ����1
�ޱce������W��¬z����w�������C�m��[�OS<|D�����ڻ��t^O��G��Pm�&��Ng�����uH�X�$^�Kp~̾Ng2�/   ���C���V�uz��O��D�z�;���^��T~�9<�?�n�U��.�#�v�z.[e9�<�֌ ��9L���uz[�1�Ħ�u����|I�x�:�:����M���ދ�gXX>0U�@���;��x��;(�o�@�%,�jp�R��U� �!s^'2\�wE�8?�TTS       ����3R���₪#ka�4D9Ak��C�L�{�9kCɥ�W&\���Z��s�Н�B�Ƕ���oՄ�L����h��*���Ty�c��Aϴ��4B,���P��Pa=��K�ny�Ӽ���2~�m�s�̈��<ÑD��s�"��3�� �oj+�\|)Ɨ(OTg|�kR4����=�BR�x���J_L����M�n�z�����Ma����q2D�����Ӌk���S�j'_E�K7E��(�@T�i�2.�P�pJm�%s�i�����ݒ�{�)r��N-__�þօc�U�9^U���y�%�ٴS帳�M}��/{ ���Y���ExR�  �a�BJyٜ���QZ�z�l�8����.���|�p� X�X�N]���m;����0Kq��y_^�j� �r���Y�r�H�-"�I$�.�H���_&�Ty���Y����$n����zS��d��q����vOěQI*ٛ�����~!S�����6B���Μ��)��`b�"i        v�w���S�t�y
��ᄭ*7�,�]��A�f��ޔ�΍;�x�vG�W���f���     ��fO��q�U�?�B5a�`���"��u�Q��K�U���7�s��c�u| �A��n��i����ee�nT�����7�%���h���d�f1Z�7
$~�鹌��     ��s-[-&���b��Y�<�:�jI�UÍ�;234�/|�C�XŴ��6����>���ݐ�7�tl/�mb�V� � ���[�ܺ�DD�Ql��4�tU�ep�o��C�rP~�s��u�#F���ܴ/-��]=��D��$K5aN�a�l��j�� �]��(�"5M �%q8��2���CD�YW�V�rǷ�
ɪ�B�=BU"w%E��2���.(Ť����G�pqA���J�#2*#��@�$���E���E���Ly
�jL��50&r�]�|׷�����m�bh^������t(b�U��M��gB"&+ӸGp��'��m�n�W�$�lUi�pH5I1B_%c�o�D�&\S;UB��c��;dе��l9�Ig�πzF�C��˷����b2U]�dr�V�:TiJ���!Z�;S�̌=���`Tܓ�=����Pkhm�UT���,�d~��+O-�Q�1��|��Z\�q�k�g-z�twt�Nd�?�  ��&�:�
���V�j�Of7��&��q.���5@�   .�[�E��zIShSx�Ǳ�)5��1C���ԓH&����_�`�*�y�H�S�v�)���z����4Rxm�'�FQ%��1,v=�N���"� -�/԰�F
'_7t�]�ͅ�#�~�).2ϣ�'�D�s�q=��&�r�       b�]ܓ�*�"��bSp��$�-p�%���j�oE_�^��u/�Y�;�bޒ�YU��\�h8�����
&��0>�fO��̔L�F��]TWև�     �r��I�=�'_�)�܁��M>�A]�����\�fcht�i�u����Vz+{����yB@���xWzƺxvd�tw�oj��'�@��=n;M����x��m$��an_�&��ɲ����q���I��Z�R�d�&5��˅Gz]X�2|����]:��X� ��)�|-���܋����K�bG�����vP��QКU�أ��h��#c0    b:ܩ��k���Dw>W3�P�Q@��D�O�u�Za���
�n�7)+O�����ڄ�"w�Z��y/�I���a����ss�v��]]?�bmЗ��H��#�8�Iv�-�]Ku3*��4��{h�_�����t��wr�]�\q�X}W��L�j��͆�$p�������:�-��|g&��Jרjc�%�*=U,jV�1}�լ:.
)��c6OL��M.�N�� O�|��bQ�bQ��y]X?�I�7�����C�u:�>�G_�34�N��G�u%����"[~4NEb� |�h �:�]�e�"dSTp,C�~�W���^m�F���yT����   ���>=�X]����Kl�Or`�{��3؄H��o�i+<�}Me�����fŬك9j@k���
C@�>�8��    ���|.�--&�o�O��1�.�pף8V�Ս'0���;.i ����V?��&�i��{c��cq�%��җ�L���g��؂?�{v�׹Qm�Lp'q��2�y��S�>�:Yy���`A��V��.��ʻ�+{�OI6�O_�(�Ƣ꧟�k>d�"����뒮==8N����U�>�O_��b���r�b��b^ ��W������uR�)�H���`�)�h�����������tn�G��F�Kri����r�}#m�>�UG(��ʜ["~��s��tf���t��l$7�i9�i���}~�����A���MãZK���}~?��ӹ�瘜+�NP����T�4]�u�$����s������}�Λ����8�ܭ�KQ�M���j�qPo����o������{�}���p!$s�"�z���x�{��噼    xp�o���������?��Z��v�����\����?�\�q3�q�!��_a�~�Cx�>�?�H�h�.C������Y���4�\����B����:�G���������;���F~�����w\�'�'����鿾�Ot��t����U�[5��s<�7dM�=&�<���aq\eG��    18������.�_yr�|dH�����S(:��=��O��ߋ?���&�w��5~�~ ���^���?f��4�������rO��t�NHf�%c82;��A��������<g����F�1a�����?�$�?�6����Mu�
1-02 13:05:01 [WARNING] nonebot_plugin_twitter | 通过 user_name mmmmmakura 获取时间线失败：403 ��� ?���_��(���R�uvh�.����PJ;;pN�)Wi�0�Ңo��{���`?��x�����LiG"F���禞����[����{\�       ��\' ��e�O�i佌�?�"�4GĘ��M����8%�W���ؕ6��g     Ǧ۠I����v�旼�]Sk.���� �ۻחy��G�`��:�� �~�Qm5�o���(n�(+f�NZ5�\��؞V��tL�\}u{���9�R�H��dh�&(Zk�>�]���c       +����#�� �6��c7�jN�~��E�     o���$��6��kO[0�h�)�gAڗ�^�>���� ��Ӹz��xu]U$�i��NZ�K�󣱙US k+��Z��<������篿�U�?Og��=�6�<���<'�����q��9�>�<��Ӻ���=һ�������:�GV��<�I$     <��IpN��L��錦pB�0��(
�s�����>��i��Z����3J��>s�%���Ә�����e�J�X����qu^@���,XҪ       @�BD�Y��"��9nz{�.��~����=r��I���t�@<�G�S�{����>Of    ��t���{�|���b*fKӶ&y{O�I��\���U�yy ��H{ET�=ð�s�t^Fl�W>�������t�5�糬|�z@$��F�>�_;
9/H���c�qt�{���ē�t��>��m��<����*�5!�����%s@5C6EgB���&,Q�{�j4��z�����c��l���#���(~0�'$Ѽ�Q�Zez=D6��&+�7!��w}�^boH�a���bpU�Tl�S=�)����    �;��(C��R6JS)4� KZ��ì�r�BAծ$tg��*��0[�<�|2�:
j� �ۂU?^b���ʋ�!�cǷ�#�g�%a*��Ʒ�#�$�J޺�Fk�E�Ѵ
�C���a7����j��8B��C.���8g�]Uш��\��y�ݦ���I�1���CB����BT�f�����q�M���i�X���F�a��Y
��,��wsү+/-S�4G�ωb�`�r�M4㠇0R���F��C�;'����^���H��R:w��aRVu�K_�oQ:w�b&d���P$j2.�Wq �u[SF�m�'S�"<���&�9)�Û�T̜�w{`9���5��z��&���^��M���uw�(�b(�.�X��Ac�2\f?���4�t
������wi����LR�   �at �M/���W����/��#�^�x�j���P����o�2���|��Z0��xg ε���|p���K\����]�y��Q�޳P���SZ���Þ�FYM��x�s#�&��W
};�BT7q�n��*����B!�( 1O5п��+&,�-�q=c��L"��B2� ~\�F՝ In-�����P�N���]"Q֘3z�#$�M �xqn�oW%^�%�Pe�0�p�xАh��q��m�   j9�R��q��]��*Co^�89˫Er�g�^T�,(!]%N�DT;��#z"[��"p�
~��tzΧ���y&�&m!�/0Xc�Nm3�=����f���2c/!D���]�0����c��"�k�(3�x�vr�$�����О��v�S.�;ȡ�V��^K���&m��rV��p��z�/`O(���0�c�k9h'0���H�C�p����ﯽ�GNV?M0���3 �Q�̳�;��Wך@0b4d���rˆJ䔽�5�<O��g�1}�Z}��ݭ���`2{��"U�S�5��]a��"�DV���<S�hI��vJ?р� �S���Z2]4jJ��sMx��z��@��S5`5��㸚�F��9?xGR<<B���)�gp\'��v𹙅�E3{\���{�m�
ccՃA���Dx��E0f�~ g�Z�����lFNa_>��cB,�����:]�b��zL1s]��B��Z1�ߤ��58IB.�D������6��4}����yr����-���9{��,/�����@�k'z�Xf'��MSF!��&f�:\��I��ޤZ���'�+C8*�. ���m�ŉ 2���7�T��4^���2i�i
�Ҡ9���[��I���Ak���� �@����Bc~t������L9C椱���t-Ok�^[�-%�)�Fp*frCnB���H��Ѹ# �N�ގoQ�J"�B�6��}���D��u�peC��>�($�Yת�DGm�~�h�x�����.���ejz��x�O��J�\�Ǥ&��U�c��%��acb��R��D<�{��u`V�o���歾`�������]�:-j{E��x���ˈ���x��#1�&!��y�k�D$�J��}!o�g4\��U�
�PP��T�(�숎���^s,@zS��j��,B�w��+[(�㹠0�R�Vs�]�SxYY�D�_y�6lw�~E�����ͼ��+o+po�i�*��r A�D�c�
HI���qy��c��2Z"=CB�ۦ�k?.�j�8ﳠ��I&2�"��A]��&.�jG�'�շ;�I���b�u@�6�j;�ddT Pı��AH�N#�j���`p�X�YA��OQ���A�3]����4�HxRB縬(�Q���3�V��僻l���$�
>� �}�`����ۊ������akq%��٣0����U����ʦ$�j*\n��i��*ԁQlGFHw薔ȩ
��0���s���|�A/!��@��:t�
�xĕp��,d�j���F�i7��W���`���krmI9��T.�l/���D����v��;)�XB����F�^�ѽ�^��G7�
͖+.w)wA�D~l#�S��s̵�*�m�l��p��k)F���J��b��G��y�k\>O�@��H�p�E-��7iyp�Kc��aSs�Cs�_��&���1�<�����6        �%�)���-sj3�zѸ)��z�K���ֹ)��;�9Ү�t/�q}��U=�Ms�Ms�]�} �xM�d��H�Z�_����<�-�s����霶���p�@v���63�K�����|LE�"�졥b�i;�ۑe���V�����䀯����� /�~� y�h/1y���P�~plW�e&f9���Y��R��۝��$yaP��@�ٝ�S���A��7�����Ս��eA�������g�Ž�V^`�z@�[��  �T2
ҥzh�Z[�i��WȽ�L�֝H
��R�Lm��ފ�����\���ٍ�t�G�&�y>����H
���������Z�U65R�a�Rti5���j`Tk�fPݶd��C�vl=�p�l��Zɫ����<�;�?��pw1{�=��x7/^�}$�e�:�ϟ���D����T�f���Л��_����<i���L�q���l������      A��{�y:+Ѽ;�Wd�\$:)~���^���!2��e�#���%�u~/����(�D\�(��{�2�
-�}}����t&v�^%���n���U3����G�y:�PK�2)F��V\^#]����QS�V�Xӏ�K�1����}�?O����]  S���FӁl�?�p��$l��E�`d4�b����矧3<��b/qL_��o�ј�Iً\�E"4T\��@~�:�����5OQߝ�Nq-M��?�1  愯�&i�o�)�~>����i�N_��G�@�ً���?��<��1���(��}�%+������'?����3�f�L��� �*����~}�����C�1&iN�����􏯯��<��y>}BqH�sI�׍�E±w��.��.��u$
�3��.q���?�S�HO��"]�9��?'R�K�{�9��刺�`<u�����s�Mr�q�ǘ��)�%��v���ʑ<����  YB6�(�u�Br���߮.s������E{��$�����_�ŀ��������a�~���M�

**Comment by Nenot233** [comment]
配置
#nonebot-plugin-twitter
twitter_proxy="http://127.0.0.1:7890"
command_priority=5
twitter_original=true
twitter_node=false

**Comment by nek0us** [comment]
配置文件里先设置这个
```bash
twitter_website="https://nitter.mint.lgbt"
```
至于乱码，可能是你shell的字符集问题
