### ISSUE TITLE
开启网页截图模式后运行报错

### ISSUE THREAD

**Issue by korin5** [nek0us/nonebot-plugin-twitter#19]
![image](https://github.com/nek0us/nonebot-plugin-twitter/assets/63297666/530302b1-615d-4082-9075-e2bfa556972f)

**Comment by nek0us** [comment]
系统是centos7吗

**Comment by korin5** [comment]
> 系统是centos7吗

系统是 Ubuntu 18.04.6 LTS

**Comment by nek0us** [comment]
是glibc版本低了导致的，不过比起升级它，可以先试试降低pywt版本
```bash
pip install playwright==1.16.1
```
如果1.16.1还报错就试试1.11.1

**Comment by korin5** [comment]
> 是glibc版本低了导致的，不过比起升级它，可以先试试降低pywt版本
> 
> ```shell
> pip install playwright==1.16.1
> ```
> 
> 如果1.16.1还报错就试试1.11.1

解决了！！非常感谢！！
