### ISSUE TITLE
无法运行插件

### ISSUE THREAD

**Issue by mzukaa1231** [nek0us/nonebot-plugin-twitter#2]
你好 请问这是什么原因？
![image](https://github.com/nek0us/nonebot-plugin-twitter/assets/136165701/21d3569f-3d18-4a22-a292-deea1026e069)

**Comment by nek0us** [comment]
那就改为 pip 安装

**Comment by nek0us** [comment]
> > 那就改为 pip 安装
> 
> 为什么不支持脚手架安装(

我也是看到这个issue才发现这回事，暂不清楚原因

**Comment by nek0us** [comment]
> > 我也是看到这个issue才发现这回事，暂不清楚原因
> 
> 有个疑问 推文推送开启得+id 那么不使用关注推主指令只用推文推送开启也可以吗

推文推送开关是一个私聊/群聊 推送的总开关，不用加id。这个指令的使用前提是有关注的推主。如果没有的话这两指令是不生效的，因为本身就没有可推送的。

**Comment by nek0us** [comment]
> > 推文推送开关是一个私聊/群聊 推送的总开关，不用加id。这个指令的使用前提是有关注的推主。如果没有的话这两指令是不生效的，因为本身就没有可推送的。
> 
> 我搞清楚了 多个群不同关注开启推送就需要+id

没有，看了下代码，是我的问题，已修复。请更新0.1.7版本

**Comment by nek0us** [comment]
> > 没有，看了下代码，是我的问题，已修复。请更新0.1.7版本
> 
> 不支持py3.10?😥

支持，我bot环境就是3.10
