### ISSUE TITLE
No module named 'nonebot_plugin_twitter'

### ISSUE THREAD

**Issue by Conkine** [nek0us/nonebot-plugin-twitter#22]
使用pip安装，添加pyproject.toml后出现的问题

05-03 21:55:58 [ERROR] nonebot | Failed to import "nonebot_plugin_twitter"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\nonebot\plugin\load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\nonebot\plugin\load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 203, in load_all_plugins
    return set(
  File "C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: **No module named 'nonebot_plugin_twitter'**

**Comment by Conkine** [comment]
1. **安装时日志**

Administrator@hcss-ecs-529f MINGW64 ~/Desktop/Nonebot/Nonebot-ciallo
$ pip install nonebot-plugin-twitter
Requirement already satisfied: nonebot-plugin-twitter in c:\program files\python\lib\site-packages (0.2.4)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\program files\python\lib\site-packages (from nonebot-plugin-twitter) (4.12.3)
Requirement already satisfied: httpx>=0.23.0 in c:\program files\python\lib\site-packages (from nonebot-plugin-twitter) (0.27.0)
Requirement already satisfied: nonebot-adapter-onebot>=2.1.3 in c:\program files\python\lib\site-packages (from nonebot-plugin-twitter) (2.4.3)
Requirement already satisfied: nonebot2>=2.0.0 in c:\program files\python\lib\site-packages (from nonebot-plugin-twitter) (2.2.1)
Requirement already satisfied: nonebot_plugin_apscheduler>=0.2.0 in c:\program files\python\lib\site-packages (from nonebot-plugin-twitter) (0.4.0)
Requirement already satisfied: nonebot_plugin_sendmsg_by_bots>=0.0.4 in c:\program files\python\lib\site-packages (from nonebot-plugin-twitter) (0.1.4)
Requirement already satisfied: playwright in c:\program files\python\lib\site-packages (from nonebot-plugin-twitter) (1.43.0)
Requirement already satisfied: soupsieve>1.2 in c:\program files\python\lib\site-packages (from beautifulsoup4>=4.11.1->nonebot-plugin-twitter) (2.5)
Requirement already satisfied: anyio in c:\program files\python\lib\site-packages (from httpx>=0.23.0->nonebot-plugin-twitter) (4.3.0)
Requirement already satisfied: certifi in c:\program files\python\lib\site-packages (from httpx>=0.23.0->nonebot-plugin-twitter) (2020.6.20)
Requirement already satisfied: httpcore==1.* in c:\program files\python\lib\site-packages (from httpx>=0.23.0->nonebot-plugin-twitter) (1.0.5)
Requirement already satisfied: idna in c:\program files\python\lib\site-packages (from httpx>=0.23.0->nonebot-plugin-twitter) (2.10)
Requirement already satisfied: sniffio in c:\program files\python\lib\site-packages (from httpx>=0.23.0->nonebot-plugin-twitter) (1.3.1)
Requirement already satisfied: h11<0.15,>=0.13 in c:\program files\python\lib\site-packages (from httpcore==1.*->httpx>=0.23.0->nonebot-plugin-twitter) (0.14.0)
Requirement already satisfied: h2<5,>=3 in c:\program files\python\lib\site-packages (from httpx[http2]>=0.25.0->nonebot-plugin-twitter) (4.1.0)
Requirement already satisfied: msgpack<2.0.0,>=1.0.3 in c:\program files\python\lib\site-packages (from nonebot-adapter-onebot>=2.1.3->nonebot-plugin-twitter) (1.0.8)
Requirement already satisfied: pydantic!=2.5.0,!=2.5.1,<3.0.0,>=1.10.0 in c:\program files\python\lib\site-packages (from nonebot-adapter-onebot>=2.1.3->nonebot-plugin-twitter) (2.7.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.0.0 in c:\program files\python\lib\site-packages (from nonebot-adapter-onebot>=2.1.3->nonebot-plugin-twitter) (4.11.0)
Requirement already satisfied: apscheduler<4.0.0,>=3.7.0 in c:\program files\python\lib\site-packages (from nonebot_plugin_apscheduler>=0.2.0->nonebot-plugin-twitter) (3.10.4)
Requirement already satisfied: loguru<1.0.0,>=0.6.0 in c:\program files\python\lib\site-packages (from nonebot2>=2.0.0->nonebot-plugin-twitter) (0.7.2)
Requirement already satisfied: pygtrie<3.0.0,>=2.4.1 in c:\program files\python\lib\site-packages (from nonebot2>=2.0.0->nonebot-plugin-twitter) (2.5.0)
Requirement already satisfied: python-dotenv<2.0.0,>=0.21.0 in c:\program files\python\lib\site-packages (from nonebot2>=2.0.0->nonebot-plugin-twitter) (1.0.1)
Requirement already satisfied: tomli<3.0.0,>=2.0.1 in c:\program files\python\lib\site-packages (from nonebot2>=2.0.0->nonebot-plugin-twitter) (2.0.1)
Requirement already satisfied: yarl<2.0.0,>=1.7.2 in c:\program files\python\lib\site-packages (from nonebot2>=2.0.0->nonebot-plugin-twitter) (1.9.4)
Requirement already satisfied: greenlet==3.0.3 in c:\program files\python\lib\site-packages (from playwright->nonebot-plugin-twitter) (3.0.3)
Requirement already satisfied: pyee==11.1.0 in c:\program files\python\lib\site-packages (from playwright->nonebot-plugin-twitter) (11.1.0)
Requirement already satisfied: six>=1.4.0 in c:\program files\python\lib\site-packages (from apscheduler<4.0.0,>=3.7.0->nonebot_plugin_apscheduler>=0.2.0->nonebot-plugin-twitter) (1.15.0)
Requirement already satisfied: pytz in c:\program files\python\lib\site-packages (from apscheduler<4.0.0,>=3.7.0->nonebot_plugin_apscheduler>=0.2.0->nonebot-plugin-twitter) (2020.1)
Requirement already satisfied: tzlocal!=3.*,>=2.0 in c:\program files\python\lib\site-packages (from apscheduler<4.0.0,>=3.7.0->nonebot_plugin_apscheduler>=0.2.0->nonebot-plugin-twitter) (5.2)
Requirement already satisfied: hyperframe<7,>=6.0 in c:\program files\python\lib\site-packages (from h2<5,>=3->httpx[http2]>=0.25.0->nonebot-plugin-twitter) (6.0.1)
Requirement already satisfied: hpack<5,>=4.0 in c:\program files\python\lib\site-packages (from h2<5,>=3->httpx[http2]>=0.25.0->nonebot-plugin-twitter) (4.0.0)
Requirement already satisfied: colorama>=0.3.4 in c:\program files\python\lib\site-packages (from loguru<1.0.0,>=0.6.0->nonebot2>=2.0.0->nonebot-plugin-twitter) (0.4.3)
Requirement already satisfied: win32-setctime>=1.0.0 in c:\program files\python\lib\site-packages (from loguru<1.0.0,>=0.6.0->nonebot2>=2.0.0->nonebot-plugin-twitter) (1.1.0)
Requirement already satisfied: annotated-types>=0.4.0 in c:\program files\python\lib\site-packages (from pydantic!=2.5.0,!=2.5.1,<3.0.0,>=1.10.0->nonebot-adapter-onebot>=2.1.3->nonebot-plugin-twitter) (0.6.0)
Requirement already satisfied: pydantic-core==2.18.1 in c:\program files\python\lib\site-packages (from pydantic!=2.5.0,!=2.5.1,<3.0.0,>=1.10.0->nonebot-adapter-onebot>=2.1.3->nonebot-plugin-twitter) (2.18.1)
Requirement already satisfied: multidict>=4.0 in c:\program files\python\lib\site-packages (from yarl<2.0.0,>=1.7.2->nonebot2>=2.0.0->nonebot-plugin-twitter) (6.0.5)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\program files\python\lib\site-packages (from anyio->httpx>=0.23.0->nonebot-plugin-twitter) (1.2.1)
Requirement already satisfied: tzdata in c:\program files\python\lib\site-packages (from tzlocal!=3.*,>=2.0->apscheduler<4.0.0,>=3.7.0->nonebot_plugin_apscheduler>=0.2.0->nonebot-plugin-twitter) (2024.1)
Requirement already satisfied: backports.zoneinfo in c:\program files\python\lib\site-packages (from tzlocal!=3.*,>=2.0->apscheduler<4.0.0,>=3.7.0->nonebot_plugin_apscheduler>=0.2.0->nonebot-plugin-twitter) (0.2.1)

Administrator@hcss-ecs-529f MINGW64 ~/Desktop/Nonebot/Nonebot-ciallo
$

**Comment by nek0us** [comment]
这个插件目前用不了，不过你这里是环境混淆了
pip的记录显示，你是装在了c盘64位安装目录，
```bash
$ pip install nonebot-plugin-twitter
Requirement already satisfied: nonebot-plugin-twitter in c:\program files\python\lib\site-packages (0.2.4)
```
然后你运行nonebot的环境是用nb-cli创建的虚拟python环境 Nonebot-ciallo.venv
```bash
File "C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo.venv\Lib\site-packages\nonebot\plugin\load.py", line 131, in load_from_toml
return load_all_plugins(plugins, plugin_dirs)
```

**Comment by Conkine** [comment]
> 这个插件目前用不了，不过你这里是环境混淆了 pip的记录显示，你是装在了c盘64位安装目录，
> 
> ```shell
> $ pip install nonebot-plugin-twitter
> Requirement already satisfied: nonebot-plugin-twitter in c:\program files\python\lib\site-packages (0.2.4)
> ```
> 
> 然后你运行nonebot的环境是用nb-cli创建的虚拟python环境 Nonebot-ciallo.venv
> 
> ```shell
> File "C:\Users\Administrator\Desktop\Nonebot\Nonebot-ciallo.venv\Lib\site-packages\nonebot\plugin\load.py", line 131, in load_from_toml
> return load_all_plugins(plugins, plugin_dirs)
> ```

 我运行nb一直都是nb-cli啊？假设插件可用，该如何解决
