### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by a1232580** [nek0us/nonebot-plugin-twitter#5]
06-13 23:28:59 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_twitter) failed.                           Traceback (most recent call last):                                 File "<string>", line 15, in <module>                            File "/root/df/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 309, in run                                            get_driver().run(*args, **kwargs)                              File "/root/df/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 198, in run                                     uvicorn.run(                                                   File "/root/df/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 578, in run                                                server.run()                                                   File "/root/df/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run                                               return asyncio.run(self.serve(sockets=sockets))                File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run     return loop.run_until_complete(main)                           File "/root/df/.venv/lib/python3.10/site-packages/nonebot/message.py", line 467, in check_and_run_matcher                           await _run_matcher(                                          > File "/root/df/.venv/lib/python3.10/site-packages/nonebot/message.py", line 419, in _run_matcher                                    await matcher.run(bot, event, state, stack, dependency_cache)  File "/root/df/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 753, in run                            await self.simple_run(bot, event, state, stack, dependency_cache)                                                               File "/root/df/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 728, in simple_run                     await handler(                                                 File "/root/df/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__                          return await cast(Callable[..., Awaitable[R]], self.call)(**values)                                                             File "/root/df/.venv/lib/python3.10/site-packages/nonebot_plugin_twitter/__init__.py", line 196, in save_handle                     user_info = await get_user_info(data[0])                       File "/root/df/.venv/lib/python3.10/site-packages/nonebot_plugin_twitter/api.py", line 23, in get_user_info                         result["screen_name"] = soup.find_all('a', class_='profile-card-fullname')[0].next                                            IndexError: list index out of range

**Comment by a1232580** [comment]
尝试关注某个推主 然后没有反应。后台有报错。

**Comment by nek0us** [comment]
> 尝试关注某个推主 然后没有反应。后台有报错。

用最新版插件

**Comment by a1232580** [comment]
> 

我这是最新版吗╰─ source .venv/bin/activate                                  ─╯
╭─    ~/df      ✔  df   root@localhost  21:45:17  ─╮
╰─ pip install nonebot-plugin-twitter                         ─╯
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Requirement already satisfied: nonebot-plugin-twitter in ./.venv/lib/python3.10/site-packages (0.1.5)
Requirement already satisfied: beautifulsoup4>=4.11.1 in ./.venv/lib/python3.10/site-packages (from nonebot-plugin-twitter) (4.12.2)
Requirement already satisfied: httpx>=0.23.0 in ./.venv/lib/python3.10/site-packages (from nonebot-plugin-twitter) (0.24.1)
Requirement already satisfied: nonebot-adapter-onebot>=2.1.3 in ./.venv/lib/python3.10/site-packages (from nonebot-plugin-twitter) (2.2.3)
Requirement already satisfied: nonebot2>=2.0.0 in ./.venv/lib/python3.10/site-packages (from nonebot-plugin-twitter) (2.0.0)
Requirement already satisfied: nonebot_plugin_apscheduler>=0.2.0 in ./.venv/lib/python3.10/site-packages (from nonebot-plugin-twitter) (0.2.0)
Requirement already satisfied: soupsieve>1.2 in ./.venv/lib/python3.10/site-packages (from beautifulsoup4>=4.11.1->nonebot-plugin-twitter) (2.4.1)
Requirement already satisfied: certifi in ./.venv/lib/python3.10/site-packages (from httpx>=0.23.0->nonebot-plugin-twitter) (2023.5.7)
Requirement already satisfied: httpcore<0.18.0,>=0.15.0 in ./.venv/lib/python3.10/site-packages (from httpx>=0.23.0->nonebot-plugin-twitter) (0.16.3)
Requirement already satisfied: idna in ./.venv/lib/python3.10/site-packages (from httpx>=0.23.0->nonebot-plugin-twitter) (3.4)
Requirement already satisfied: sniffio in ./.venv/lib/python3.10/site-packages (from httpx>=0.23.0->nonebot-plugin-twitter) (1.3.0)
Requirement already satisfied: msgpack<2.0.0,>=1.0.3 in ./.venv/lib/python3.10/site-packages (from nonebot-adapter-onebot>=2.1.3->nonebot-plugin-twitter) (1.0.5)
Requirement already satisfied: apscheduler<4.0.0,>=3.7.0 in ./.venv/lib/python3.10/site-packages (from nonebot_plugin_apscheduler>=0.2.0->nonebot-plugin-twitter) (3.10.1)
Requirement already satisfied: loguru<1.0.0,>=0.6.0 in ./.venv/lib/python3.10/site-packages (from nonebot2>=2.0.0->nonebot-plugin-twitter) (0.7.0)
Requirement already satisfied: pydantic[dotenv]<2.0.0,>=1.10.0 in ./.venv/lib/python3.10/site-packages (from nonebot2>=2.0.0->nonebot-plugin-twitter) (1.10.9)
Requirement already satisfied: pygtrie<3.0.0,>=2.4.1 in ./.venv/lib/python3.10/site-packages (from nonebot2>=2.0.0->nonebot-plugin-twitter) (2.5.0)
Requirement already satisfied: tomli<3.0.0,>=2.0.1 in ./.venv/lib/python3.10/site-packages (from nonebot2>=2.0.0->nonebot-plugin-twitter) (2.0.1)
Requirement already satisfied: typing-extensions<5.0.0,>=4.0.0 in ./.venv/lib/python3.10/site-packages (from nonebot2>=2.0.0->nonebot-plugin-twitter) (4.6.3)
Requirement already satisfied: yarl<2.0.0,>=1.7.2 in ./.venv/lib/python3.10/site-packages (from nonebot2>=2.0.0->nonebot-plugin-twitter) (1.9.2)
Requirement already satisfied: setuptools>=0.7 in ./.venv/lib/python3.10/site-packages (from apscheduler<4.0.0,>=3.7.0->nonebot_plugin_apscheduler>=0.2.0->nonebot-plugin-twitter) (65.6.3)
Requirement already satisfied: six>=1.4.0 in ./.venv/lib/python3.10/site-packages (from apscheduler<4.0.0,>=3.7.0->nonebot_plugin_apscheduler>=0.2.0->nonebot-plugin-twitter) (1.16.0)
Requirement already satisfied: pytz in ./.venv/lib/python3.10/site-packages (from apscheduler<4.0.0,>=3.7.0->nonebot_plugin_apscheduler>=0.2.0->nonebot-plugin-twitter) (2023.3)
Requirement already satisfied: tzlocal!=3.*,>=2.0 in ./.venv/lib/python3.10/site-packages (from apscheduler<4.0.0,>=3.7.0->nonebot_plugin_apscheduler>=0.2.0->nonebot-plugin-twitter) (5.0.1)
Requirement already satisfied: h11<0.15,>=0.13 in ./.venv/lib/python3.10/site-packages (from httpcore<0.18.0,>=0.15.0->httpx>=0.23.0->nonebot-plugin-twitter) (0.14.0)
Requirement already satisfied: anyio<5.0,>=3.0 in ./.venv/lib/python3.10/site-packages (from httpcore<0.18.0,>=0.15.0->httpx>=0.23.0->nonebot-plugin-twitter) (3.7.0)
Requirement already satisfied: python-dotenv>=0.10.4 in ./.venv/lib/python3.10/site-packages (from pydantic[dotenv]<2.0.0,>=1.10.0->nonebot2>=2.0.0->nonebot-plugin-twitter) (1.0.0)
Requirement already satisfied: multidict>=4.0 in ./.venv/lib/python3.10/site-packages (from yarl<2.0.0,>=1.7.2->nonebot2>=2.0.0->nonebot-plugin-twitter) (6.0.4)
Requirement already satisfied: exceptiongroup in ./.venv/lib/python3.10/site-packages (from anyio<5.0,>=3.0->httpcore<0.18.0,>=0.15.0->httpx>=0.23.0->nonebot-plugin-twitter) (1.1.1)
如果是的话，那不行。

**Comment by a1232580** [comment]
能正常使用，有些可以关注 但是也有些博主关注不了会报错。

**Comment by nek0us** [comment]
> 

不是最新版，最新版版本号在readme上有显示，查询版本命令可以用 
```bash 
pip list | grep 插件名```，升级命令```bash
pip install 插件名 --upgrade```

**Comment by a1232580** [comment]
> > 
> 
> 不是最新版，最新版版本号在readme上有显示，查询版本命令可以用
> 
> ```shell
> pip list | grep 插件名
> ```
> 
> 升级命令
> 
> ```shell
> pip install 插件名 --upgrade
> ```

好的 没有问题了

**Comment by nek0us** [comment]
> > ```shell
> > pip install 插件名 --upgrade
> > ```
> 
> 06-20 00:06:47 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_twitter) failed. Traceback (most recent call last): File "C:\robot.venv\lib\site-packages\httpx_transports\default.py", line 60, in map_httpcore_exceptions yield File "C:\robot.venv\lib\site-packages\httpx_transports\default.py", line 353, in handle_async_request resp = await self._pool.handle_async_request(req) File "C:\robot.venv\lib\site-packages\httpcore_async\connection_pool.py", line 208, in handle_async_request raise UnsupportedProtocol( httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "", line 17, in File "C:\robot.venv\lib\site-packages\nonebot__init__.py", line 309, in run get_driver().run(*args, **kwargs) File "C:\robot.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run uvicorn.run( File "C:\robot.venv\lib\site-packages\uvicorn\main.py", line 578, in run server.run() File "C:\robot.venv\lib\site-packages\uvicorn\server.py", line 61, in run return asyncio.run(self.serve(sockets=sockets)) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_unt il_complete self.run_forever() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_ forever super().run_forever() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_for ever self._run_once() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_o nce handle._run() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run self._context.run(self._callback, *self._args) File "C:\robot.venv\lib\site-packages\nonebot\message.py", line 467, in check_and_run_matcher await _run_matcher(
> 
> > File "C:\robot.venv\lib\site-packages\nonebot\message.py", line 419, in _run_matcher
> > await matcher.run(bot, event, state, stack, dependency_cache)
> > File "C:\robot.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
> > await self.simple_run(bot, event, state, stack, dependency_cache)
> > File "C:\robot.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
> > await handler(
> > File "C:\robot.venv\lib\site-packages\nonebot\dependencies__init__.py", line 108, in **call**
> > return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> > File "C:\robot.venv\lib\site-packages\nonebot_plugin_twitter__init__.py", line 196, in save_handle
> > user_info = await get_user_info(data[0])
> > File "C:\robot.venv\lib\site-packages\nonebot_plugin_twitter\api.py", line 17, in get_user_info
> > res = await client.get(url=f"{config_dev.twitter_url}/{user_name}")
> > File "C:\robot.venv\lib\site-packages\httpx_client.py", line 1757, in get
> > return await self.request(
> > File "C:\robot.venv\lib\site-packages\httpx_client.py", line 1533, in request
> > return await self.send(request, auth=auth, follow_redirects=follow_redirects)
> > File "C:\robot.venv\lib\site-packages\httpx_client.py", line 1620, in send
> > response = await self._send_handling_auth(
> > File "C:\robot.venv\lib\site-packages\httpx_client.py", line 1648, in _send_handling_auth
> > response = await self._send_handling_redirects(
> > File "C:\robot.venv\lib\site-packages\httpx_client.py", line 1685, in _send_handling_redirects
> > response = await self._send_single_request(request)
> > File "C:\robot.venv\lib\site-packages\httpx_client.py", line 1722, in _send_single_request
> > response = await transport.handle_async_request(request)
> > File "C:\robot.venv\lib\site-packages\httpx_transports\default.py", line 352, in handle_async_request
> > with map_httpcore_exceptions():
> > File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in **exit**
> > self.gen.throw(typ, value, traceback)
> > File "C:\robot.venv\lib\site-packages\httpx_transports\default.py", line 77, in map_httpcore_exceptions
> > raise mapped_exc(message) from exc
> > httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
> 
> 大佬 这是什么

配置文件里代理格式不对吧？http代理记得加http://前缀
```bash
http://127.0.0.1:8080
```
这样

**Comment by nek0us** [comment]
> > 插件更新到最新版了吗？
> 
> 没事了 我把opencv-python删除就好了

暂不清楚是什么原因导致冲突了，下次再出现可以附上报错前后nonebot日志
