### ISSUE TITLE
推主转推只拉取原推文，无附加图文回复

### ISSUE THREAD

**Issue by fankongwxy** [nek0us/nonebot-plugin-twitter#8]
若推主多次转发同一推文发表内容，则多次推送转发的原推文
如下：
![图片](https://github.com/nek0us/nonebot-plugin-twitter/assets/51537416/19757620-785c-421f-8334-97f581ad96dd)
则BOT推送3次完全相同的内容：
2500億円って、本当に金の卵を産むガチョウをほふる行為なのだけど、これが国の舵取りしてる人の考える事なのですかね。
これ10年スパンとかで本当にエンタメ産業壊滅させますよ。
たかだか2500億円のために何やりたいんだか。

**Comment by nek0us** [comment]
试试最新版，可能还不太完善，后续还会更新优化这个
